const pictures = [
  { id: 0, src: require("../assets/pictures/all/antelope.jpg") },
  { id: 1, src: require("../assets/pictures/all/bear.jpg") },
  { id: 2, src: require("../assets/pictures/all/bee.jpg") },
  { id: 3, src: require("../assets/pictures/all/beetle.jpg") },
  { id: 4, src: require("../assets/pictures/all/butterfly.jpg") },
  { id: 5, src: require("../assets/pictures/all/cat.jpg") },
  { id: 6, src: require("../assets/pictures/all/caterpillar.jpg") },
  { id: 7, src: require("../assets/pictures/all/chimpanzee.jpg") },
  { id: 8, src: require("../assets/pictures/all/cow.jpg") },
  { id: 9, src: require("../assets/pictures/all/coyote.jpg") },
  { id: 10, src: require("../assets/pictures/all/crab.jpg") },
  { id: 11, src: require("../assets/pictures/all/crow.jpg") },
  { id: 12, src: require("../assets/pictures/all/deer.jpg") },
  { id: 13, src: require("../assets/pictures/all/dog.jpg") },
  { id: 14, src: require("../assets/pictures/all/dolphin.jpg") },
  { id: 15, src: require("../assets/pictures/all/donkey.jpg") },
  { id: 16, src: require("../assets/pictures/all/dragonfly.jpg") },
  { id: 17, src: require("../assets/pictures/all/duck.jpg") },
  { id: 18, src: require("../assets/pictures/all/eagle.jpg") },
  { id: 19, src: require("../assets/pictures/all/elephant.jpg") },
  { id: 20, src: require("../assets/pictures/all/flamingo.jpg") },
  { id: 21, src: require("../assets/pictures/all/fly.jpg") },
  { id: 22, src: require("../assets/pictures/all/fox.jpg") },
  { id: 23, src: require("../assets/pictures/all/goat.jpg") },
  { id: 24, src: require("../assets/pictures/all/goldfish.jpg") },
  { id: 25, src: require("../assets/pictures/all/goose.jpg") },
  { id: 26, src: require("../assets/pictures/all/gorilla.jpg") },
  { id: 27, src: require("../assets/pictures/all/grasshopper.jpg") },
  { id: 28, src: require("../assets/pictures/all/hamster.jpg") },
  { id: 29, src: require("../assets/pictures/all/rabbit.jpg") },
  { id: 30, src: require("../assets/pictures/all/hippopotamus.jpg") },
  { id: 31, src: require("../assets/pictures/all/horse.jpg") },
  { id: 32, src: require("../assets/pictures/all/hummingbird.jpg") },
  { id: 33, src: require("../assets/pictures/all/jellyfish.jpg") },
  { id: 34, src: require("../assets/pictures/all/kangaroo.jpg") },
  { id: 35, src: require("../assets/pictures/all/koala.jpg") },
  { id: 36, src: require("../assets/pictures/all/ladybugs.jpg") },
  { id: 37, src: require("../assets/pictures/all/leopard.jpg") },
  { id: 38, src: require("../assets/pictures/all/lion.jpg") },
  //   { id: 39, src: "../assets/pictures/all/lobster.jpg" },
  //   { id: 40, src: "../assets/pictures/all/owl.jpg" },
  //   { id: 41, src: "../assets/pictures/all/ox.jpg" },
  //   { id: 42, src: "../assets/pictures/all/oyster.jpg" },
  //   { id: 43, src: "../assets/pictures/all/panda.jpg" },
  //   { id: 44, src: "../assets/pictures/all/parrot.jpg" },
  //   { id: 45, src: "../assets/pictures/all/penguin.jpg" },
  //   { id: 46, src: "../assets/pictures/all/pig.jpg" },
  //   { id: 47, src: "../assets/pictures/all/pigeon.jpg" },
  //   { id: 48, src: "../assets/pictures/all/porcupine.jpg" },
  //   { id: 49, src: "../assets/pictures/all/raccoon.jpg" },
  //   { id: 50, src: "../assets/pictures/all/reindeer.jpg" },
  //   { id: 51, src: "../assets/pictures/all/rhinoceros.jpg" },
  //   { id: 52, src: "../assets/pictures/all/seahorse.jpg" },
  //   { id: 53, src: "../assets/pictures/all/seal.jpg" },
  //   { id: 54, src: "../assets/pictures/all/shark.jpg" },
  //   { id: 55, src: "../assets/pictures/all/sheep.jpg" },
  //   { id: 56, src: "../assets/pictures/all/snake.jpg" },
  //   { id: 57, src: "../assets/pictures/all/sparrow.jpg" },
  //   { id: 58, src: "../assets/pictures/all/squirrel.jpg" },
  //   { id: 59, src: "../assets/pictures/all/starfish.jpg" },
  //   { id: 60, src: "../assets/pictures/all/swan.jpg" },
  //   { id: 61, src: "../assets/pictures/all/tiger.jpg" },
  //   { id: 62, src: "../assets/pictures/all/turtle.jpg" },
  //   { id: 63, src: "../assets/pictures/all/whale.jpg" },
  //   { id: 64, src: "../assets/pictures/all/wolf.jpg" },
  //   { id: 65, src: "../assets/pictures/all/woodpecker.jpg" },
  //   { id: 66, src: "../assets/pictures/all/zebra.jpg" },
  //   { id: 67, src: "../assets/pictures/all/apple.jpg" },
  //   { id: 68, src: "../assets/pictures/all/banana.jpg" },
  //   { id: 69, src: "../assets/pictures/all/bell pepper.jpg" },
  //   { id: 70, src: "../assets/pictures/all/cabbage.jpg" },
  //   { id: 71, src: "../assets/pictures/all/carrot.jpg" },
  //   { id: 72, src: "../assets/pictures/all/cauliflower.jpg" },
  //   { id: 73, src: "../assets/pictures/all/chilli pepper.jpg" },
  //   { id: 74, src: "../assets/pictures/all/corn.jpg" },
  //   { id: 75, src: "../assets/pictures/all/cucumber.jpg" },
  //   { id: 76, src: "../assets/pictures/all/eggplant.jpg" },
  //   { id: 77, src: "../assets/pictures/all/garlic.jpg" },
  //   { id: 78, src: "../assets/pictures/all/ginger.jpg" },
  //   { id: 79, src: "../assets/pictures/all/grapes.jpg" },
  //   { id: 80, src: "../assets/pictures/all/jalepeno.jpg" },
  //   { id: 81, src: "../assets/pictures/all/kiwi.jpg" },
  //   { id: 82, src: "../assets/pictures/all/lemon.jpg" },
  //   { id: 83, src: "../assets/pictures/all/lettuce.jpg" },
  //   { id: 84, src: "../assets/pictures/all/mango.jpg" },
  //   { id: 85, src: "../assets/pictures/all/onion.jpg" },
  //   { id: 86, src: "../assets/pictures/all/orange.jpg" },
  //   { id: 87, src: "../assets/pictures/all/paprika.jpg" },
  //   { id: 88, src: "../assets/pictures/all/pear.jpg" },
  //   { id: 89, src: "../assets/pictures/all/peas.jpg" },
  //   { id: 90, src: "../assets/pictures/all/pineapple.jpg" },
  //   { id: 91, src: "../assets/pictures/all/potato.jpg" },
  //   { id: 92, src: "../assets/pictures/all/raddish.jpg" },
  //   { id: 93, src: "../assets/pictures/all/soy beans.jpg" },
  //   { id: 94, src: "../assets/pictures/all/spinach.jpg" },
  //   { id: 95, src: "../assets/pictures/all/sweetpotato.jpg" },
  //   { id: 96, src: "../assets/pictures/all/tomato.jpg" },
  //   { id: 97, src: "../assets/pictures/all/watermelon.jpg" },
  //   { id: 98, src: "../assets/pictures/all/t shirt.jpg" },
  //   { id: 99, src: "../assets/pictures/all/longsleeve.jpg" },
  //   { id: 100, src: "../assets/pictures/all/pants.jpg" },
  //   { id: 101, src: "../assets/pictures/all/shoes.jpg" },
  //   { id: 102, src: "../assets/pictures/all/shirt.jpg" },
  //   { id: 103, src: "../assets/pictures/all/dress.jpg" },
  //   { id: 104, src: "../assets/pictures/all/jacket.jpg" },
  //   { id: 105, src: "../assets/pictures/all/shorts.jpg" },
  //   { id: 106, src: "../assets/pictures/all/hat.jpg" },
  //   { id: 107, src: "../assets/pictures/all/skirt.jpg" },
  //   { id: 108, src: "../assets/pictures/all/polo.jpg" },
  //   { id: 109, src: "../assets/pictures/all/blazer.jpg" },
  //   { id: 110, src: "../assets/pictures/all/raincoat.jpg" },
  //   { id: 111, src: "../assets/pictures/all/hoodie.jpg" },
  //   { id: 112, src: "../assets/pictures/all/slippers.jpg" },
  //   { id: 113, src: "../assets/pictures/all/sandals.jpg" },
  //   { id: 114, src: "../assets/pictures/all/tie.jpg" },
  //   { id: 115, src: "../assets/pictures/all/bow tie.jpg" },
  //   { id: 116, src: "../assets/pictures/all/socks.jpg" },
  //   { id: 117, src: "../assets/pictures/all/sunglass.jpg" },
  //   { id: 118, src: "../assets/pictures/all/glasses.jpg" },
  //   { id: 119, src: "../assets/pictures/all/washing machine.jpg" },
  //   { id: 120, src: "../assets/pictures/all/phone.jpg" },
  //   { id: 121, src: "../assets/pictures/all/air conditioner.jpg" },
  //   { id: 122, src: "../assets/pictures/all/laptop.jpg" },
  //   { id: 123, src: "../assets/pictures/all/television.jpg" },
  //   { id: 124, src: "../assets/pictures/all/fridge.jpg" },
  //   { id: 125, src: "../assets/pictures/all/remote.jpg" },
  //   { id: 126, src: "../assets/pictures/all/gaming console.jpg" },
  //   { id: 127, src: "../assets/pictures/all/fan.jpg" },
  //   { id: 128, src: "../assets/pictures/all/light bulb.jpg" },
  //   { id: 129, src: "../assets/pictures/all/camera.jpg" },
  //   { id: 130, src: "../assets/pictures/all/headphone.jpg" },
  //   { id: 131, src: "../assets/pictures/all/calculator.jpg" },
  //   { id: 132, src: "../assets/pictures/all/speaker.jpg" },
  //   { id: 133, src: "../assets/pictures/all/microphone.jpg" },
  //   { id: 134, src: "../assets/pictures/all/hair dryer.jpg" },
  //   { id: 135, src: "../assets/pictures/all/printer.jpg" },
  //   { id: 136, src: "../assets/pictures/all/iron.jpg" },
  //   { id: 137, src: "../assets/pictures/all/oven.jpg" },
  //   { id: 138, src: "../assets/pictures/all/microwave.jpg" },
  //   { id: 139, src: "../assets/pictures/all/pen.jpg" },
  //   { id: 140, src: "../assets/pictures/all/pencil.jpg" },
  //   { id: 141, src: "../assets/pictures/all/notebook.jpg" },
  //   { id: 142, src: "../assets/pictures/all/sharpner.jpg" },
  //   { id: 143, src: "../assets/pictures/all/scale.jpg" },
  //   { id: 144, src: "../assets/pictures/all/compass.jpg" },
  //   { id: 145, src: "../assets/pictures/all/book.jpg" },
  //   { id: 146, src: "../assets/pictures/all/eraser.jpg" },
  //   { id: 147, src: "../assets/pictures/all/scissors.jpg" },
  //   { id: 148, src: "../assets/pictures/all/glue.jpg" },
  //   { id: 149, src: "../assets/pictures/all/highlighter.jpg" },
  //   { id: 150, src: "../assets/pictures/all/stapler.jpg" },
  //   { id: 151, src: "../assets/pictures/all/folder.jpg" },
  //   { id: 152, src: "../assets/pictures/all/tape.jpg" },
  //   { id: 153, src: "../assets/pictures/all/bed.jpg" },
  //   { id: 154, src: "../assets/pictures/all/closet.jpg" },
  //   { id: 155, src: "../assets/pictures/all/chair.jpg" },
  //   { id: 156, src: "../assets/pictures/all/couch.jpg" },
  //   { id: 157, src: "../assets/pictures/all/clock.jpg" },
  //   { id: 158, src: "../assets/pictures/all/desk.jpg" },
  //   { id: 159, src: "../assets/pictures/all/table.jpg" },
  //   { id: 160, src: "../assets/pictures/all/carpet.jpg" },
  //   { id: 161, src: "../assets/pictures/all/piano.jpg" },
  //   { id: 162, src: "../assets/pictures/all/flute.jpg" },
  //   { id: 163, src: "../assets/pictures/all/bell.jpg" },
  //   { id: 164, src: "../assets/pictures/all/harp.jpg" },
  //   { id: 165, src: "../assets/pictures/all/drum.jpg" },
  //   { id: 166, src: "../assets/pictures/all/xylophone.jpg" },
  //   { id: 167, src: "../assets/pictures/all/banjo.jpg" },
  //   { id: 168, src: "../assets/pictures/all/guitar.jpg" },
  //   { id: 169, src: "../assets/pictures/all/saxophone.jpg" },
  //   { id: 170, src: "../assets/pictures/all/clarinet.jpg" },
  //   { id: 171, src: "../assets/pictures/all/violin.jpg" },
  //   { id: 172, src: "../assets/pictures/all/harmonica.jpg" },
  //   { id: 173, src: "../assets/pictures/all/keyboard.jpg" },
  //   { id: 174, src: "../assets/pictures/all/chocolate.jpg" },
  //   { id: 175, src: "../assets/pictures/all/egg.jpg" },
  //   { id: 176, src: "../assets/pictures/all/candy.jpg" },
  //   { id: 177, src: "../assets/pictures/all/cake.jpg" },
  //   { id: 178, src: "../assets/pictures/all/cookies.jpg" },
  //   { id: 179, src: "../assets/pictures/all/burger.jpg" },
  //   { id: 180, src: "../assets/pictures/all/pizza.jpg" },
  //   { id: 181, src: "../assets/pictures/all/pasta.jpg" },
  //   { id: 182, src: "../assets/pictures/all/salad.jpg" },
  //   { id: 183, src: "../assets/pictures/all/bread.jpg" },
  //   { id: 184, src: "../assets/pictures/all/noodles.jpg" },
  //   { id: 185, src: "../assets/pictures/all/chips.jpg" },
  //   { id: 186, src: "../assets/pictures/all/tacos.jpg" },
  //   { id: 187, src: "../assets/pictures/all/curry.jpg" },
  //   { id: 188, src: "../assets/pictures/all/soccer.jpg" },
  //   { id: 189, src: "../assets/pictures/all/rugby.jpg" },
  //   { id: 190, src: "../assets/pictures/all/hockey.jpg" },
  //   { id: 191, src: "../assets/pictures/all/cricket.jpg" },
  //   { id: 192, src: "../assets/pictures/all/swimming.jpg" },
  //   { id: 193, src: "../assets/pictures/all/volleyball.jpg" },
  //   { id: 194, src: "../assets/pictures/all/archery.jpg" },
  //   { id: 195, src: "../assets/pictures/all/tennis.jpg" },
  //   { id: 196, src: "../assets/pictures/all/basketball.jpg" },
  //   { id: 197, src: "../assets/pictures/all/baseball.jpg" },
  //   { id: 198, src: "../assets/pictures/all/table tennis.jpg" },
  //   { id: 199, src: "../assets/pictures/all/badminton.jpg" },
  //   { id: 200, src: "../assets/pictures/all/horse riding.jpg" },
  //   { id: 201, src: "../assets/pictures/all/lacrosse.jpg" },
  //   { id: 202, src: "../assets/pictures/all/judo.jpg" },
  //   { id: 203, src: "../assets/pictures/all/bowling.jpg" },
  //   { id: 204, src: "../assets/pictures/all/ice hockey.jpg" },
  //   { id: 205, src: "../assets/pictures/all/athletics.jpg" },
  //   { id: 206, src: "../assets/pictures/all/fencing.jpg" },
  //   { id: 207, src: "../assets/pictures/all/cycling.jpg" },
  //   { id: 208, src: "../assets/pictures/all/car.jpg" },
  //   { id: 209, src: "../assets/pictures/all/bus.jpg" },
  //   { id: 210, src: "../assets/pictures/all/train.jpg" },
  //   { id: 211, src: "../assets/pictures/all/cycle.jpg" },
  //   { id: 212, src: "../assets/pictures/all/jeep.jpg" },
  //   { id: 213, src: "../assets/pictures/all/truck.jpg" },
  //   { id: 214, src: "../assets/pictures/all/airplane.jpg" },
  //   { id: 215, src: "../assets/pictures/all/ship.jpg" },
  //   { id: 216, src: "../assets/pictures/all/submarine.jpg" },
  //   { id: 217, src: "../assets/pictures/all/tank.jpg" },
  //   { id: 218, src: "../assets/pictures/all/scooter.jpg" },
  //   { id: 219, src: "../assets/pictures/all/bike.jpg" },
  //   { id: 220, src: "../assets/pictures/all/key.jpg" },
  //   { id: 221, src: "../assets/pictures/all/towel.jpg" },
  //   { id: 222, src: "../assets/pictures/all/newspaper.jpg" },
];

export default pictures;
