const pictures = [
  {
    id: 0,
    src: require("../assets/pictures/all/antelope.jpg"),
    word: "antelope",
  },
  { id: 1, src: require("../assets/pictures/all/bear.jpg"), word: "bear" },
  { id: 2, src: require("../assets/pictures/all/bee.jpg"), word: "bee" },
  { id: 3, src: require("../assets/pictures/all/beetle.jpg"), word: "beetle" },
  {
    id: 4,
    src: require("../assets/pictures/all/butterfly.jpg"),
    word: "butterfly",
  },
  { id: 5, src: require("../assets/pictures/all/cat.jpg"), word: "cat" },
  {
    id: 6,
    src: require("../assets/pictures/all/caterpillar.jpg"),
    word: "caterpillar",
  },
  {
    id: 7,
    src: require("../assets/pictures/all/chimpanzee.jpg"),
    word: "chimpanzee",
  },
  { id: 8, src: require("../assets/pictures/all/cow.jpg"), word: "cow" },
  { id: 9, src: require("../assets/pictures/all/coyote.jpg"), word: "coyote" },
  { id: 10, src: require("../assets/pictures/all/crab.jpg"), word: "crab" },
  { id: 11, src: require("../assets/pictures/all/crow.jpg"), word: "crow" },
  { id: 12, src: require("../assets/pictures/all/deer.jpg"), word: "deer" },
  { id: 13, src: require("../assets/pictures/all/dog.jpg"), word: "dog" },
  {
    id: 14,
    src: require("../assets/pictures/all/dolphin.jpg"),
    word: "dolphin",
  },
  { id: 15, src: require("../assets/pictures/all/donkey.jpg"), word: "donkey" },
  {
    id: 16,
    src: require("../assets/pictures/all/dragonfly.jpg"),
    word: "dragonfly",
  },
  { id: 17, src: require("../assets/pictures/all/duck.jpg"), word: "duck" },
  { id: 18, src: require("../assets/pictures/all/eagle.jpg"), word: "eagle" },
  {
    id: 19,
    src: require("../assets/pictures/all/elephant.jpg"),
    word: "elephant",
  },
  {
    id: 20,
    src: require("../assets/pictures/all/flamingo.jpg"),
    word: "flamingo",
  },
  { id: 21, src: require("../assets/pictures/all/fly.jpg"), word: "fly" },
  { id: 22, src: require("../assets/pictures/all/fox.jpg"), word: "fox" },
  { id: 23, src: require("../assets/pictures/all/goat.jpg"), word: "goat" },
  {
    id: 24,
    src: require("../assets/pictures/all/goldfish.jpg"),
    word: "goldfish",
  },
  { id: 25, src: require("../assets/pictures/all/goose.jpg"), word: "goose" },
  {
    id: 26,
    src: require("../assets/pictures/all/gorilla.jpg"),
    word: "gorilla",
  },
  {
    id: 27,
    src: require("../assets/pictures/all/grasshopper.jpg"),
    word: "grasshopper",
  },
  {
    id: 28,
    src: require("../assets/pictures/all/hamster.jpg"),
    word: "hamster",
  },
  { id: 29, src: require("../assets/pictures/all/rabbit.jpg"), word: "rabbit" },
  {
    id: 30,
    src: require("../assets/pictures/all/hippopotamus.jpg"),
    word: "hippopotamus",
  },
  { id: 31, src: require("../assets/pictures/all/horse.jpg"), word: "horse" },
  {
    id: 32,
    src: require("../assets/pictures/all/hummingbird.jpg"),
    word: "hummingbird",
  },
  {
    id: 33,
    src: require("../assets/pictures/all/jellyfish.jpg"),
    word: "jellyfish",
  },
  {
    id: 34,
    src: require("../assets/pictures/all/kangaroo.jpg"),
    word: "kangaroo",
  },
  { id: 35, src: require("../assets/pictures/all/koala.jpg"), word: "koala" },
  {
    id: 36,
    src: require("../assets/pictures/all/ladybugs.jpg"),
    word: "ladybugs",
  },
  {
    id: 37,
    src: require("../assets/pictures/all/leopard.jpg"),
    word: "leopard",
  },
  { id: 38, src: require("../assets/pictures/all/lion.jpg"), word: "lion" },
  {
    id: 39,
    src: require("../assets/pictures/all/lobster.jpg"),
    word: "lobster",
  },
  { id: 40, src: require("../assets/pictures/all/owl.jpg"), word: "owl" },
  { id: 41, src: require("../assets/pictures/all/ox.jpg"), word: "ox" },
  { id: 42, src: require("../assets/pictures/all/oyster.jpg"), word: "oyster" },
  { id: 43, src: require("../assets/pictures/all/panda.jpg"), word: "panda" },
  { id: 44, src: require("../assets/pictures/all/parrot.jpg"), word: "parrot" },
  {
    id: 45,
    src: require("../assets/pictures/all/penguin.jpg"),
    word: "penguin",
  },
  { id: 46, src: require("../assets/pictures/all/pig.jpg"), word: "pig" },
  { id: 47, src: require("../assets/pictures/all/pigeon.jpg"), word: "pigeon" },
  {
    id: 48,
    src: require("../assets/pictures/all/porcupine.jpg"),
    word: "porcupine",
  },
  {
    id: 49,
    src: require("../assets/pictures/all/raccoon.jpg"),
    word: "raccoon",
  },
  {
    id: 50,
    src: require("../assets/pictures/all/reindeer.jpg"),
    word: "reindeer",
  },
  {
    id: 51,
    src: require("../assets/pictures/all/rhinoceros.jpg"),
    word: "rhinoceros",
  },
  {
    id: 52,
    src: require("../assets/pictures/all/seahorse.jpg"),
    word: "seahorse",
  },
  { id: 53, src: require("../assets/pictures/all/seal.jpg"), word: "seal" },
  { id: 54, src: require("../assets/pictures/all/shark.jpg"), word: "shark" },
  { id: 55, src: require("../assets/pictures/all/sheep.jpg"), word: "sheep" },
  { id: 56, src: require("../assets/pictures/all/snake.jpg"), word: "snake" },
  {
    id: 57,
    src: require("../assets/pictures/all/sparrow.jpg"),
    word: "sparrow",
  },
  {
    id: 58,
    src: require("../assets/pictures/all/squirrel.jpg"),
    word: "squirrel",
  },
  {
    id: 59,
    src: require("../assets/pictures/all/starfish.jpg"),
    word: "starfish",
  },
  { id: 60, src: require("../assets/pictures/all/swan.jpg"), word: "swan" },
  { id: 61, src: require("../assets/pictures/all/tiger.jpg"), word: "tiger" },
  { id: 62, src: require("../assets/pictures/all/turtle.jpg"), word: "turtle" },
  { id: 63, src: require("../assets/pictures/all/whale.jpg"), word: "whale" },
  { id: 64, src: require("../assets/pictures/all/wolf.jpg"), word: "wolf" },
  {
    id: 65,
    src: require("../assets/pictures/all/woodpecker.jpg"),
    word: "woodpecker",
  },
  { id: 66, src: require("../assets/pictures/all/zebra.jpg"), word: "zebra" },
  { id: 67, src: require("../assets/pictures/all/apple.jpg"), word: "apple" },
  { id: 68, src: require("../assets/pictures/all/banana.jpg"), word: "banana" },
  {
    id: 69,
    src: require("../assets/pictures/all/bell_pepper.jpg"),
    word: "bell pepper",
  },
  {
    id: 70,
    src: require("../assets/pictures/all/cabbage.jpg"),
    word: "cabbage",
  },
  { id: 71, src: require("../assets/pictures/all/carrot.jpg"), word: "carrot" },
  {
    id: 72,
    src: require("../assets/pictures/all/cauliflower.jpg"),
    word: "cauliflower",
  },
  {
    id: 73,
    src: require("../assets/pictures/all/chilli_pepper.jpg"),
    word: "chilli pepper",
  },
  { id: 74, src: require("../assets/pictures/all/corn.jpg"), word: "corn" },
  {
    id: 75,
    src: require("../assets/pictures/all/cucumber.jpg"),
    word: "cucumber",
  },
  {
    id: 76,
    src: require("../assets/pictures/all/eggplant.jpg"),
    word: "eggplant",
  },
  { id: 77, src: require("../assets/pictures/all/garlic.jpg"), word: "garlic" },
  { id: 78, src: require("../assets/pictures/all/ginger.jpg"), word: "ginger" },
  { id: 79, src: require("../assets/pictures/all/grapes.jpg"), word: "grapes" },
  {
    id: 80,
    src: require("../assets/pictures/all/jalepeno.jpg"),
    word: "jalepeno",
  },
  { id: 81, src: require("../assets/pictures/all/kiwi.jpg"), word: "kiwi" },
  { id: 82, src: require("../assets/pictures/all/lemon.jpg"), word: "lemon" },
  {
    id: 83,
    src: require("../assets/pictures/all/lettuce.jpg"),
    word: "lettuce",
  },
  { id: 84, src: require("../assets/pictures/all/mango.jpg"), word: "mango" },
  { id: 85, src: require("../assets/pictures/all/onion.jpg"), word: "onion" },
  { id: 86, src: require("../assets/pictures/all/orange.jpg"), word: "orange" },
  {
    id: 87,
    src: require("../assets/pictures/all/paprika.jpg"),
    word: "paprika",
  },
  { id: 88, src: require("../assets/pictures/all/pear.jpg"), word: "pear" },
  { id: 89, src: require("../assets/pictures/all/peas.jpg"), word: "peas" },
  {
    id: 90,
    src: require("../assets/pictures/all/pineapple.jpg"),
    word: "pineapple",
  },
  { id: 91, src: require("../assets/pictures/all/potato.jpg"), word: "potato" },
  {
    id: 92,
    src: require("../assets/pictures/all/raddish.jpg"),
    word: "raddish",
  },
  {
    id: 93,
    src: require("../assets/pictures/all/soy_beans.jpg"),
    word: "soy beans",
  },
  {
    id: 94,
    src: require("../assets/pictures/all/spinach.jpg"),
    word: "spinach",
  },
  {
    id: 95,
    src: require("../assets/pictures/all/sweetpotato.jpg"),
    word: "sweetpotato",
  },
  { id: 96, src: require("../assets/pictures/all/tomato.jpg"), word: "tomato" },
  {
    id: 97,
    src: require("../assets/pictures/all/watermelon.jpg"),
    word: "watermelon",
  },
  {
    id: 98,
    src: require("../assets/pictures/all/t_shirt.jpg"),
    word: "t shirt",
  },
  {
    id: 99,
    src: require("../assets/pictures/all/longsleeve.jpg"),
    word: "longsleeve",
  },
  { id: 100, src: require("../assets/pictures/all/pants.jpg"), word: "pants" },
  { id: 101, src: require("../assets/pictures/all/shoes.jpg"), word: "shoes" },
  { id: 102, src: require("../assets/pictures/all/shirt.jpg"), word: "shirt" },
  { id: 103, src: require("../assets/pictures/all/dress.jpg"), word: "dress" },
  {
    id: 104,
    src: require("../assets/pictures/all/jacket.jpg"),
    word: "jacket",
  },
  {
    id: 105,
    src: require("../assets/pictures/all/shorts.jpg"),
    word: "shorts",
  },
  { id: 106, src: require("../assets/pictures/all/hat.jpg"), word: "hat" },
  { id: 107, src: require("../assets/pictures/all/skirt.jpg"), word: "skirt" },
  { id: 108, src: require("../assets/pictures/all/polo.jpg"), word: "polo" },
  {
    id: 109,
    src: require("../assets/pictures/all/blazer.jpg"),
    word: "blazer",
  },
  {
    id: 110,
    src: require("../assets/pictures/all/raincoat.jpg"),
    word: "raincoat",
  },
  {
    id: 111,
    src: require("../assets/pictures/all/hoodie.jpg"),
    word: "hoodie",
  },
  {
    id: 112,
    src: require("../assets/pictures/all/slippers.jpg"),
    word: "slippers",
  },
  {
    id: 113,
    src: require("../assets/pictures/all/sandals.jpg"),
    word: "sandals",
  },
  { id: 114, src: require("../assets/pictures/all/tie.jpg"), word: "tie" },
  {
    id: 115,
    src: require("../assets/pictures/all/bow_tie.jpg"),
    word: "bow tie",
  },
  { id: 116, src: require("../assets/pictures/all/socks.jpg"), word: "socks" },
  {
    id: 117,
    src: require("../assets/pictures/all/sunglass.jpg"),
    word: "sunglass",
  },
  {
    id: 118,
    src: require("../assets/pictures/all/glasses.jpg"),
    word: "glasses",
  },
  {
    id: 119,
    src: require("../assets/pictures/all/washing_machine.jpg"),
    word: "washing machine",
  },
  { id: 120, src: require("../assets/pictures/all/phone.jpg"), word: "phone" },
  {
    id: 121,
    src: require("../assets/pictures/all/air_conditioner.jpg"),
    word: "air conditioner",
  },
  {
    id: 122,
    src: require("../assets/pictures/all/laptop.jpg"),
    word: "laptop",
  },
  {
    id: 123,
    src: require("../assets/pictures/all/television.jpg"),
    word: "television",
  },
  {
    id: 124,
    src: require("../assets/pictures/all/fridge.jpg"),
    word: "fridge",
  },
  {
    id: 125,
    src: require("../assets/pictures/all/remote.jpg"),
    word: "remote",
  },
  {
    id: 126,
    src: require("../assets/pictures/all/gaming_console.jpg"),
    word: "gaming console",
  },
  { id: 127, src: require("../assets/pictures/all/fan.jpg"), word: "fan" },
  {
    id: 128,
    src: require("../assets/pictures/all/light_bulb.jpg"),
    word: "light bulb",
  },
  {
    id: 129,
    src: require("../assets/pictures/all/camera.jpg"),
    word: "camera",
  },
  {
    id: 130,
    src: require("../assets/pictures/all/headphone.jpg"),
    word: "headphone",
  },
  {
    id: 131,
    src: require("../assets/pictures/all/calculator.jpg"),
    word: "calculator",
  },
  {
    id: 132,
    src: require("../assets/pictures/all/speaker.jpg"),
    word: "speaker",
  },
  {
    id: 133,
    src: require("../assets/pictures/all/microphone.jpg"),
    word: "microphone",
  },
  {
    id: 134,
    src: require("../assets/pictures/all/hair_dryer.jpg"),
    word: "hair dryer",
  },
  {
    id: 135,
    src: require("../assets/pictures/all/printer.jpg"),
    word: "printer",
  },
  { id: 136, src: require("../assets/pictures/all/iron.jpg"), word: "iron" },
  { id: 137, src: require("../assets/pictures/all/oven.jpg"), word: "oven" },
  {
    id: 138,
    src: require("../assets/pictures/all/microwave.jpg"),
    word: "microwave",
  },
  { id: 139, src: require("../assets/pictures/all/pen.jpg"), word: "pen" },
  {
    id: 140,
    src: require("../assets/pictures/all/pencil.jpg"),
    word: "pencil",
  },
  {
    id: 141,
    src: require("../assets/pictures/all/notebook.jpg"),
    word: "notebook",
  },
  {
    id: 142,
    src: require("../assets/pictures/all/sharpner.jpg"),
    word: "sharpner",
  },
  { id: 143, src: require("../assets/pictures/all/scale.jpg"), word: "scale" },
  {
    id: 144,
    src: require("../assets/pictures/all/compass.jpg"),
    word: "compass",
  },
  { id: 145, src: require("../assets/pictures/all/book.jpg"), word: "book" },
  {
    id: 146,
    src: require("../assets/pictures/all/eraser.jpg"),
    word: "eraser",
  },
  {
    id: 147,
    src: require("../assets/pictures/all/scissors.jpg"),
    word: "scissors",
  },
  { id: 148, src: require("../assets/pictures/all/glue.jpg"), word: "glue" },
  {
    id: 149,
    src: require("../assets/pictures/all/highlighter.jpg"),
    word: "highlighter",
  },
  {
    id: 150,
    src: require("../assets/pictures/all/stapler.jpg"),
    word: "stapler",
  },
  {
    id: 151,
    src: require("../assets/pictures/all/folder.jpg"),
    word: "folder",
  },
  { id: 152, src: require("../assets/pictures/all/tape.jpg"), word: "tape" },
  { id: 153, src: require("../assets/pictures/all/bed.jpg"), word: "bed" },
  {
    id: 154,
    src: require("../assets/pictures/all/closet.jpg"),
    word: "closet",
  },
  { id: 155, src: require("../assets/pictures/all/chair.jpg"), word: "chair" },
  { id: 156, src: require("../assets/pictures/all/couch.jpg"), word: "couch" },
  { id: 157, src: require("../assets/pictures/all/clock.jpg"), word: "clock" },
  { id: 158, src: require("../assets/pictures/all/desk.jpg"), word: "desk" },
  { id: 159, src: require("../assets/pictures/all/table.jpg"), word: "table" },
  {
    id: 160,
    src: require("../assets/pictures/all/carpet.jpg"),
    word: "carpet",
  },
  { id: 161, src: require("../assets/pictures/all/piano.jpg"), word: "piano" },
  { id: 162, src: require("../assets/pictures/all/flute.jpg"), word: "flute" },
  { id: 163, src: require("../assets/pictures/all/bell.jpg"), word: "bell" },
  { id: 164, src: require("../assets/pictures/all/harp.jpg"), word: "harp" },
  { id: 165, src: require("../assets/pictures/all/drum.jpg"), word: "drum" },
  {
    id: 166,
    src: require("../assets/pictures/all/xylophone.jpg"),
    word: "xylophone",
  },
  { id: 167, src: require("../assets/pictures/all/banjo.jpg"), word: "banjo" },
  {
    id: 168,
    src: require("../assets/pictures/all/guitar.jpg"),
    word: "guitar",
  },
  {
    id: 169,
    src: require("../assets/pictures/all/saxophone.jpg"),
    word: "saxophone",
  },
  {
    id: 170,
    src: require("../assets/pictures/all/clarinet.jpg"),
    word: "clarinet",
  },
  {
    id: 171,
    src: require("../assets/pictures/all/violin.jpg"),
    word: "violin",
  },
  {
    id: 172,
    src: require("../assets/pictures/all/harmonica.jpg"),
    word: "harmonica",
  },
  {
    id: 173,
    src: require("../assets/pictures/all/keyboard.jpg"),
    word: "keyboard",
  },
  {
    id: 174,
    src: require("../assets/pictures/all/chocolate.jpg"),
    word: "chocolate",
  },
  { id: 175, src: require("../assets/pictures/all/egg.jpg"), word: "egg" },
  { id: 176, src: require("../assets/pictures/all/candy.jpg"), word: "candy" },
  { id: 177, src: require("../assets/pictures/all/cake.jpg"), word: "cake" },
  {
    id: 178,
    src: require("../assets/pictures/all/cookies.jpg"),
    word: "cookies",
  },
  {
    id: 179,
    src: require("../assets/pictures/all/burger.jpg"),
    word: "burger",
  },
  { id: 180, src: require("../assets/pictures/all/pizza.jpg"), word: "pizza" },
  { id: 181, src: require("../assets/pictures/all/pasta.jpg"), word: "pasta" },
  { id: 182, src: require("../assets/pictures/all/salad.jpg"), word: "salad" },
  { id: 183, src: require("../assets/pictures/all/bread.jpg"), word: "bread" },
  {
    id: 184,
    src: require("../assets/pictures/all/noodles.jpg"),
    word: "noodles",
  },
  { id: 185, src: require("../assets/pictures/all/chips.jpg"), word: "chips" },
  { id: 186, src: require("../assets/pictures/all/tacos.jpg"), word: "tacos" },
  { id: 187, src: require("../assets/pictures/all/curry.jpg"), word: "curry" },
  {
    id: 188,
    src: require("../assets/pictures/all/soccer.jpg"),
    word: "soccer",
  },
  { id: 189, src: require("../assets/pictures/all/rugby.jpg"), word: "rugby" },
  {
    id: 190,
    src: require("../assets/pictures/all/hockey.jpg"),
    word: "hockey",
  },
  {
    id: 191,
    src: require("../assets/pictures/all/cricket.jpg"),
    word: "cricket",
  },
  {
    id: 192,
    src: require("../assets/pictures/all/swimming.jpg"),
    word: "swimming",
  },
  {
    id: 193,
    src: require("../assets/pictures/all/volleyball.jpg"),
    word: "volleyball",
  },
  {
    id: 194,
    src: require("../assets/pictures/all/archery.jpg"),
    word: "archery",
  },
  {
    id: 195,
    src: require("../assets/pictures/all/tennis.jpg"),
    word: "tennis",
  },
  {
    id: 196,
    src: require("../assets/pictures/all/basketball.jpg"),
    word: "basketball",
  },
  {
    id: 197,
    src: require("../assets/pictures/all/baseball.jpg"),
    word: "baseball",
  },
  {
    id: 198,
    src: require("../assets/pictures/all/table_tennis.jpg"),
    word: "table tennis",
  },
  {
    id: 199,
    src: require("../assets/pictures/all/badminton.jpg"),
    word: "badminton",
  },
  {
    id: 200,
    src: require("../assets/pictures/all/horse_riding.jpg"),
    word: "horse riding",
  },
  {
    id: 201,
    src: require("../assets/pictures/all/lacrosse.jpg"),
    word: "lacrosse",
  },
  { id: 202, src: require("../assets/pictures/all/judo.jpg"), word: "judo" },
  {
    id: 203,
    src: require("../assets/pictures/all/bowling.jpg"),
    word: "bowling",
  },
  {
    id: 204,
    src: require("../assets/pictures/all/ice_hockey.jpg"),
    word: "ice hockey",
  },
  {
    id: 205,
    src: require("../assets/pictures/all/athletics.jpg"),
    word: "athletics",
  },
  {
    id: 206,
    src: require("../assets/pictures/all/fencing.jpg"),
    word: "fencing",
  },
  {
    id: 207,
    src: require("../assets/pictures/all/cycling.jpg"),
    word: "cycling",
  },
  { id: 208, src: require("../assets/pictures/all/car.jpg"), word: "car" },
  { id: 209, src: require("../assets/pictures/all/bus.jpg"), word: "bus" },
  { id: 210, src: require("../assets/pictures/all/train.jpg"), word: "train" },
  { id: 211, src: require("../assets/pictures/all/cycle.jpg"), word: "cycle" },
  { id: 212, src: require("../assets/pictures/all/jeep.jpg"), word: "jeep" },
  { id: 213, src: require("../assets/pictures/all/truck.jpg"), word: "truck" },
  {
    id: 214,
    src: require("../assets/pictures/all/airplane.jpg"),
    word: "airplane",
  },
  { id: 215, src: require("../assets/pictures/all/ship.jpg"), word: "ship" },
  {
    id: 216,
    src: require("../assets/pictures/all/submarine.jpg"),
    word: "submarine",
  },
  { id: 217, src: require("../assets/pictures/all/tank.jpg"), word: "tank" },
  {
    id: 218,
    src: require("../assets/pictures/all/scooter.jpg"),
    word: "scooter",
  },
  { id: 219, src: require("../assets/pictures/all/bike.jpg"), word: "bike" },
  { id: 220, src: require("../assets/pictures/all/key.jpg"), word: "key" },
  { id: 221, src: require("../assets/pictures/all/towel.jpg"), word: "towel" },
  {
    id: 222,
    src: require("../assets/pictures/all/newspaper.jpg"),
    word: "newspaper",
  },
];

export default pictures;
